seed: 777
device_train_batch_size: 100
global_train_batch_size: 100
device_eval_batch_size: 100
device_train_microbatch_size: "auto"
vocabulary:
  remote: "s3://tahoe-hackathon-data/MFM/vevo_v2_vocab.json"
  local: "vocab.json"
model:
  name: tahoe_x1
  d_model: 512
  n_layers: 12
  init_device: cpu
  expansion_ratio: 4
  standard_scale_outputs: False
  transformer_activation: relu
  n_heads: 8
  norm_scheme: "pre"
  use_generative_training: True
  use_cell_conditioned_generation: False
  use_glu: False
  cell_emb_style: cls
  attn_config:
    attn_impl: torch
    attn_type: "grouped_query_attention"
    kv_nheads: 8
    attn_pdrop: 0.0
    use_attn_mask: False
  norm_config:
    norm_type: "layernorm"
    eps: 1.0e-5
  expression_encoder:
    input_emb_style: "continuous"
    dropout: 0.1
    max_value: 512
    activation: relu
    use_norm: True
  gene_encoder:
    use_norm: True
  mvc:
    arch_style: "inner product"
    query_activation: "sigmoid"
    scaled_dot_product: True
  expression_decoder:
    n_outputs: 1
    n_layers: 1
    activation: "leaky_relu"
collator:
  do_padding: True
  pad_value: -2
  do_mlm: True
  do_binning: True
  mlm_probability: 0.5
  mask_value: -1
  max_length: 1024
  sampling: True
  data_style: "both"
  num_bins: 51
  right_binning: False
  use_junk_tokens: False
train_loader:
  dataset:
    streams:
      tahoe:
        remote: "s3://tahoe-hackathon-data/MFM/tahoe_100m_MDS_v2/train/"
        local: "mds-data-folder/tahoe-100m/train"
    download_timeout: 300
    allow_unsafe_types: True
    shuffle: True
    shuffle_seed: 777
    num_canonical_nodes: 2
  drop_last: False
  num_workers: 8
  pin_memory: True
  prefetch_factor: 4
  persistent_workers: True
valid_loader:
  dataset:
    streams:
      tahoe:
        remote: "s3://tahoe-hackathon-data/MFM/tahoe_100m_MDS_v2/valid/"
        local: "mds-data-folder/tahoe-100m/val"
    download_timeout: 300
    allow_unsafe_types: True
    shuffle: False
    shuffle_seed: 777
    num_canonical_nodes: 2
  drop_last: False
  num_workers: 8
  pin_memory: True
  prefetch_factor: 4
  persistent_workers: True
optimizer:
  name: decoupled_adamw
  lr: 3.0e-4
  betas:
    - 0.9
    - 0.95
  eps: 1.0e-08
  weight_decay: 1.0e-05
scheduler:
  name: cosine_with_warmup
  t_warmup: "0.05dur"
  t_max: "1dur"
  alpha_f: 0.1
algorithms:
  gradient_clipping:
    clipping_type: norm
    clipping_threshold: 1.0
  low_precision_layernorm: {}
precision: amp_bf16
eval_interval: "1000ba"
eval_subset_num_batches: 100
max_duration: "1000ba"
fsdp_config:
  sharding_strategy: FULL_SHARD
  mixed_precision: DEFAULT
  activation_checkpointing: false
  activation_checkpointing_reentrant: false
  activation_cpu_offload: false
  limit_all_gathers: true
  verbose: true

# Logging
progress_bar: false
log_to_console: true
console_log_interval: 1ba

callbacks:
  speed_monitor:
    window_size: 20
  lr_monitor: {}
  memory_monitor: {}
  runtime_estimator: {}

# loggers:
#   wandb: {}

# Checkpoint to local filesystem or remote object store
save_interval: 500ba
save_num_checkpoints_to_keep: 1  # Important, this cleans up checkpoints saved to DISK
save_folder: ./{run_name}/checkpoints
# save_folder: s3://my-bucket/my-folder/{run_name}/checkpoints

# Load from local filesystem or remote object store
# load_path: ./tahoe-x1/checkpoints/latest-rank{rank}.pt
# load_path: s3://my-bucket/my-folder/tahoe-x1/checkpoints/latest-rank{rank}.pt
